name: stacked_notification_cards
description: A Flutter implementation of iOS style stacked notifications which can be dismissed.
repository: https://github.com/oaktreeapps/stacked_notification_cards
issue_tracker: https://github.com/oaktreeapps/stacked_notification_cards/issues

version: 0.1.0-dev.7

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^4.0.3
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
